#set page(paper: "a4", margin: 2.5cm)
#set text(font: "New Computer Modern", size: 11pt)
#set par(justify: true)

#align(center, text(14pt, weight: "bold")[
  Cyclic Subgroups and Halving
])

= Introduction

Let $F$ be a finite field. Within its non-zero elements $F^times$, we choose an element $omega$ that is a primitive root of order $2^n$, i.e. $omega^(2^n) = 1$ and no smaller positive power of $omega$ gives $1$.

From $omega$, we construct a chain of subsets $D_0, D_1, D_2, dots$ where each is obtained by squaring the previous one, $D_k = D_(k-1)^2 = {x^2 : x in D_(k-1)}$:

$D_0 := {1, omega, omega^2, omega^3, dots, omega^(2^n - 1)}$

$D_1 := {1, omega^2, omega^4, omega^6, dots, omega^(2(2^(n-1) - 1))}$

In general:

$ D_k := {1, omega^(2^k), omega^(2 dot 2^k), omega^(3 dot 2^k), dots}. $

*Def:* A *cyclic group* is one that can be generated by a single element. If we take an element $g$ and look at all its powers ${1, g, g^2, g^3, dots}$, we eventually return to $1$ (because we are in a finite group). The number of distinct elements before repeating is called the *order* of the group.

Let's see that $D_k$ is cyclic with generator $omega^(2^k)$. By definition, every element of $D_k$ is a power of $omega^(2^k)$. Since $(omega^(2^k))^(2^(n-k)) = omega^(2^n) = 1$, the powers repeat after $2^(n-k)$ steps, and no earlier (because $omega$ is primitive). Thus $D_k$ is exactly the cyclic group generated by $omega^(2^k)$.

Now the question is, for a given $k$, what's the order of $D_k$?

=== Let's start with a concrete example

Let's say $n = 3$, that is, $omega$ has order $2^3 = 8$.

- $D_0 = {1, omega, omega^2, omega^3, omega^4, omega^5, omega^6, omega^7}$.

- $D_1$ comes from squaring each element of $D_0$:

  $D_1 &= {1^2, omega^2, (omega^2)^2, (omega^3)^2, (omega^4)^2, (omega^5)^2, (omega^6)^2, (omega^7)^2}\
  &={1, omega^2, omega^4, omega^6, omega^8, omega^10, omega^12, omega^14}\
  &={1, omega^2, omega^4, omega^6, omega^0, omega^2, omega^4, omega^6}\
  &={1, omega^2, omega^4, omega^6}$

  So, $|D_0| = 8$ and $|D_1|=4$. Let's continue.

- $D_2 = {(omega^2)^2, (omega^4)^2, (omega^6)^2, 1^2} = {1, omega^4, omega^8, omega^12} = {1, omega^4, 1, omega^4} = {1, omega^4}$.

  It has $2$ elements.

- $D_3 = {1^2, (omega^4)^2} = {1, omega^8} = {1, 1} = {1}$.

  It has $1$ element.

We observe a clear pattern: $8 -> 4 -> 2 -> 1$. Each step divides by $2$.

= Hypothesis

From the example above, a natural hypothesis emerges:

For each $k < n$, the order of $D_k$ is exactly double the order of $D_(k+1)$:

$ |D_k| = 2 dot |D_(k+1)|. $

= Proof

*Theorem.* For every $k < n$, we have $|D_(k+1)| = |D_k| / 2$.

*Proof.* Consider the squaring map $phi : D_k -> D_(k+1)$ given by $phi(x) = x^2$. This map is surjective because $D_(k+1) = {x^2 : x in D_k}$ by construction.

The kernel of $phi$ consists of the elements $x in D_k$ such that $x^2 = 1$. Since $D_k$ is a cyclic group of order $2^(n-k)$ (which is even because $k < n$), the equation $x^2 = 1$ has exactly two solutions: $x = 1$ and $x = -1$. Therefore, $|ker(phi)| = 2$.

Each element of $D_(k+1)$ is the image of exactly $|ker(phi)| = 2$ elements from $D_k$. Hence:

$ |D_(k+1)| = |D_k| / |ker(phi)| = |D_k| / 2. #h(1em) checkmark $

This completes the proof.

*Observation.* By iterating this halving, we obtain $|D_k| = 2^(n-k)$ for all $k <= n$. In particular, starting from $|D_0| = 2^n$, after $n$ halvings we reach $|D_n| = 1$. In $n$ steps, the group collapses to a single element. This exponential reduction is the fundamental algebraic property that makes this structure so useful in iterative constructions.

#h(1fr) $square$
