#set page(paper: "a4", margin: 2.5cm)
#set text(font: "New Computer Modern", size: 11pt)
#set par(justify: true)

#align(center, text(14pt, weight: "bold")[
  Cyclic Subgroups and Halving
])

= Introduction

Let $F$ be a finite field. Within its non-zero elements $F^times$, we choose an element $omega$ that is a primitive root of order $2^n$ with $n >= 1$, i.e. $omega^(2^n) = 1$ and no smaller positive power of $omega$ gives $1$.

*Note:* We require $n >= 1$ so that the initial order $|D_0| = 2^n$ is even. This is the hypothesis we need for the halving to begin.

From $omega$, we construct a chain of subsets $D_0, D_1, D_2, dots$ where each is obtained by squaring the previous one, $D_k = D_(k-1)^2 = {x^2 : x in D_(k-1)}$:

$D_0 := {1, omega, omega^2, omega^3, dots, omega^(2^n - 1)}$

$D_1 := {1, omega^2, omega^4, omega^6, dots, omega^(2(2^(n-1) - 1))}$

In general:

$ D_k := {1, omega^(2^k), omega^(2 dot 2^k), omega^(3 dot 2^k), dots}. $

*Def:* A *cyclic group* is one that can be generated by a single element. If we take an element $g$ and look at all its powers ${1, g, g^2, g^3, dots}$, we eventually return to $1$ (because we are in a finite group). The number of distinct elements before repeating is called the *order* of the group.

Let's see that $D_k$ is cyclic with generator $omega^(2^k)$. By definition, every element of $D_k$ is a power of $omega^(2^k)$. Since $(omega^(2^k))^(2^(n-k)) = omega^(2^n) = 1$, the powers repeat after $2^(n-k)$ steps, and no earlier (because $omega$ is primitive). Thus $D_k$ is exactly the cyclic group generated by $omega^(2^k)$.

Now the question is, for a given $k$, what's the order of $D_k$?

=== Let's start with a concrete example

Let's say $n = 3$, that is, $omega$ has order $2^3 = 8$.

- $D_0 = {1, omega, omega^2, omega^3, omega^4, omega^5, omega^6, omega^7}$.

- $D_1$ comes from squaring each element of $D_0$:

  $D_1 &= {1^2, omega^2, (omega^2)^2, (omega^3)^2, (omega^4)^2, (omega^5)^2, (omega^6)^2, (omega^7)^2}\
  &={1, omega^2, omega^4, omega^6, omega^8, omega^10, omega^12, omega^14}\
  &={1, omega^2, omega^4, omega^6, omega^0, omega^2, omega^4, omega^6}\
  &={1, omega^2, omega^4, omega^6}$

  So, $|D_0| = 8$ and $|D_1|=4$. Let's continue.

- $D_2 = {(omega^2)^2, (omega^4)^2, (omega^6)^2, 1^2} = {1, omega^4, omega^8, omega^12} = {1, omega^4, 1, omega^4} = {1, omega^4}$.

  It has $2$ elements.

- $D_3 = {1^2, (omega^4)^2} = {1, omega^8} = {1, 1} = {1}$.

  It has $1$ element.

We observe a clear pattern: $8 arrow.r 4 arrow.r 2 arrow.r 1$. Each step divides by $2$.

#pagebreak()

= Hypothesis

From the example above, a natural hypothesis emerges:

For each $k < n$, the order of $D_k$ is exactly double the order of $D_(k+1)$:

$ |D_k| = 2 dot |D_(k+1)|. $

= Proof

*Theorem.* For every $k < n$, we have $|D_(k+1)| = (|D_k|) / 2$.

*Proof by induction on $k$.*

*Base case* ($k = 0$): We need to show $|D_1| = (|D_0|) / 2$. Recall that $D_0$ has $2^n$ elements: $D_0 = {1, omega, omega^2, dots, omega^(2^n - 1)}$. Each element of $D_1$ is the square of some element of $D_0$.

Consider the element $alpha = omega^((2^n - 1) / 2)$. Since $2^n - 1$ is odd (because $n >= 1$), the exponent $(2^n - 1) / 2$ is an integer. Let's examine $alpha$:

- First, $alpha^2 = omega^(2^n - 1) = omega^(-1) = omega^(2^n - 1) = 1$ (since $omega^(2^n) = 1$).

- Second, $alpha != 1$. If $alpha$ were $1$, then $omega^((2^n - 1) / 2) = 1$, which would mean $omega$ has order at most $(2^n - 1) / 2 < 2^n$, contradicting that $omega$ is primitive of order $2^n$.

So $alpha$ is an element of order exactly $2$ in $D_0$. In a cyclic group, there is exactly one such element: $-1$. Thus $omega^((2^n - 1) / 2) = -1$.

This gives us a clean split of $D_0$ into two halves. The first half contains the "positive" powers:

$ {1, omega, omega^2, dots, omega^((2^n - 3) / 2)} $

The second half contains their negatives:

$ {-1, -omega, -omega^2, dots, -omega^((2^n - 3) / 2)} $

Indeed, $omega^((2^n - 1) / 2) = -1$, and multiplying by $omega^j$ gives $omega^((2^n - 1) / 2 + j) = -omega^j$. As $j$ ranges from $0$ to $(2^n - 3) / 2$, we cover exactly the remaining elements of $D_0$.

Now, squaring any element from the second half gives the same result as squaring its positive counterpart, because $(-x)^2 = x^2$. Therefore, each square in $D_1$ is hit exactly twice: once by a positive element and once by its negative. The distinct elements of $D_1$ are precisely the squares of the positive half:

$ D_1 = {1, omega^2, omega^4, dots, omega^(2^n - 3)} $

This set has $(2^n) / 2 = 2^(n-1)$ elements, so $|D_1| = (|D_0|) / 2$. $checkmark$

*Inductive step:* Assume $|D_k| = 2^(n-k)$ and that $D_k$ is cyclic with generator $omega^(2^k)$ of order $2^(n-k)$. Since $n - k >= 1$ (because $k < n$), the order $2^(n-k)$ is even. We can apply the same argument to $D_k$.

The generator $omega^(2^k)$ has even order $2^(n-k)$, so by the same reasoning:

$ (omega^(2^k))^((2^(n-k) - 1) / 2) = -1 $

within $D_k$. This splits $D_k$ into positive and negative halves. Squaring collapses each pair ${x, -x}$ to a single element, so exactly half the elements survive:

$ |D_(k+1)| = (|D_k|) / 2 = 2^(n-k-1). $ $checkmark$

This completes the induction.

*Observation.* By iterating this halving, we obtain $|D_k| = 2^(n-k)$ for all $k <= n$. In particular, starting from $|D_0| = 2^n$, after $n$ halvings we reach $|D_n| = 1$. In $n$ steps, the group collapses to a single element. This exponential reduction is the fundamental algebraic property that makes this structure so useful in iterative constructions.

#h(1fr) $square$
