#set page(paper: "a4", margin: 2.5cm)
#set text(font: "New Computer Modern", size: 11pt)
#set par(justify: true)

#align(center, text(14pt, weight: "bold")[
  Cyclic Subgroups and Halving
])

= Introduction

Let $F$ be a finite field. Within its non-zero elements $F^times$, we choose an element $omega$ that is a primitive root of order $2^n$, i.e $omega^(2^n) = 1$ and no smaller positive power of $omega$ gives $1$.



From $omega$, we construct a chain of subsets $D_0, D_1, D_2, dots$ where each is the set of powers of a generator and we get the next one by squaring the previous one, $D_k$ = $D_(k-1)^2$:

D_0 := { Comentario: completar hasta un n }

D_1 := { Comentario: completar hasta un m }


In general:

$ D_k := {1, omega^(2^k), omega^(2 dot 2^k), omega^(3 dot 2^k), dots}. $



Let's also see that $D_k$ is the cyclic group generated by $omega^(2^k)$.

*Def:* A *cyclic group* is one that can be generated by a single element. If we take an element $g$ and look at all its powers ${1, g, g^2, g^3, dots}$, we eventually return to $1$ (because we are in a finite group). The number of distinct elements before repeating is called the *order* of the group.

Completar Demo de que Dk es cíclico con generador $omega^(2^k)$


Now the question is, for a given $k$, what's the order of $D_k$?

=== Let's start with a concrete example

Let's say $n = 3$, that is, $omega$ has order $2^3 = 8$.

- $D_0 = {1, omega, omega^2, omega^3, omega^4, omega^5, omega^6, omega^7}$.

- $D_1 &= {1^2, omega^2, omega^2^2, omega^3^2, omega^4^2, omega^5^2, omega^6^2, omega^7^2}\
&={1, omega^2, omega^4, omega^6, omega^8, omega^10, omega^12, omega^14}\
&={1, omega^2, omega^4, omega^6, omega^0, omega^2, omega^4, omega^6}\
&={1, omega^2, omega^4, omega^6}$

So, $|D_0| = 8$ and $|D_1|=4$. Let's continue. 

*Step 2:* $D_2 = {1, omega^2^2, omega^4^2, omega^6^2} = {1, omega^4, omega^8, omega^12} = {1, omega^4, omega^0, omega^4} = {1, omega^4}$
It has $2$ elements.

*Step 3:* $D_3 = {1, omega^4^2} = {1, omega^0} = {1}$.
It has $1$ element.

We observe a clear pattern: $8 -> 4 -> 2 -> 1$. Each step divides by $2$.

= Hypothesis

From the example above, a natural hypothesis emerges:

For each $k < n$, the order of $D_k$ is exactly double the order of $D_(k+1)$:

$ |D_k| = 2 dot |D_(k+1)|. $


= Proof

Arreglar: No hay necesidad de provar que $|D_k| = 2^(n-k)$, lo podemos dejar como observacion al final pero decir que la hipotesis es una y probar otra cosa confunde aunque sean equivalentes.

We will prove that $|D_k| = 2^(n-k)$ for all $k <= n$. This automatically implies that it halves at each step.

*Theorem.* For all $k <= n$, we have $|D_k| = 2^(n-k)$.

*Proof by induction on $k$.*

*Base case* ($k = 0$): $D_0 = angle.l omega angle.r$. Since $omega$ has order $2^n$ by definition:

$ |D_0| = 2^n = 2^(n-0). #h(1em) checkmark $

*Inductive step:* Suppose $|D_k| = 2^(n-k)$ for some $k < n$. We want to prove that $|D_(k+1)| = 2^(n-(k+1))$.

The key is to observe that $D_(k+1)$ consists exactly of the squares of the elements of $D_k$. That is:

$ D_(k+1) = {x^2 : x in D_k}. $

The mapping $x |-> x^2$ sends $D_k$ onto $D_(k+1)$. In a cyclic group of even order, the equation $x^2 = 1$ has exactly two solutions: $x = 1$ and $x = -1$. Therefore, each element of $D_(k+1)$ comes from exactly $2$ elements of $D_k$.

We conclude that:

$ |D_(k+1)| = (|D_k|) / 2 = 2^(n-k) / 2 = 2^(n-k-1) = 2^(n-(k+1)). #h(1em) checkmark $

This completes the induction.

Starting from $|D_0| = 2^n$, we end with $|D_n| = 1$. In $n$ steps, the group collapses to a single element. This exponential reduction is the fundamental algebraic property that makes this structure so useful in iterative constructions.

#h(1fr) $square$
