import Mathlib

/-
  Cyclic Subgroups and Halving

  We prove that in a finite field, starting from a primitive root ω of order 2^n,
  the chain of domains D_k obtained by repeated squaring halves in size at each step.

  Structure:
  1. Introduction: Define F, ω, and D_k
  2. Hypothesis: |D_k| = 2 · |D_{k+1}|
  3. Proof: By induction on k
-/

section Cyclic_Subgroups_and_Halving

variable {F : Type*} [Field F] [Finite F]

-- ω is a primitive 2^n-th root of unity in F^×
variable (ω : Fˣ) (n : ℕ) (hω : orderOf ω = 2 ^ n)

include hω

/- D_k is the cyclic subgroup generated by ω^(2^k).

   D_0 = ⟨ω⟩        (order 2^n)
   D_1 = ⟨ω^2⟩      (order 2^{n-1})
   D_2 = ⟨ω^4⟩      (order 2^{n-2})
   ...
   D_k = ⟨ω^(2^k)⟩  (order 2^{n-k})

   By construction, D_{k+1} = {x^2 : x ∈ D_k}.
-/

def D (k : ℕ) : Subgroup Fˣ := Subgroup.zpowers (ω ^ (2 ^ k))

/- Every element of D_k is a power of ω^(2^k).
   Since (ω^(2^k))^(2^{n-k}) = ω^(2^n) = 1 and ω is primitive,
   the powers repeat after exactly 2^{n-k} steps.
   Thus D_k is the cyclic group generated by ω^(2^k).
-/

/- The cardinality of D_k equals the order of its generator.
   We use: orderOf(ω^(2^k)) = orderOf(ω) / gcd(orderOf(ω), 2^k) = 2^n / 2^k = 2^{n-k}.
-/

theorem D_card (k : ℕ) (hk : k ≤ n) :
    Nat.card (D ω k) = 2 ^ (n - k) := by
  unfold D
  rw [Nat.card_zpowers]
  rw [orderOf_pow, hω]
  have h_gcd : Nat.gcd (2 ^ n) (2 ^ k) = 2 ^ k := by
    have h_dvd : 2 ^ k ∣ 2 ^ n := by exact Nat.pow_dvd_pow 2 (by omega)
    rw [Nat.gcd_comm]
    exact Nat.gcd_eq_left h_dvd
  rw [h_gcd]
  exact Nat.pow_div (by omega) (by norm_num)

/-
   Main Theorem (Hypothesis): |D_{k+1}| = |D_k| / 2.

   Proof by induction on k.

   Base case (k = 0):
   |D_0| = 2^n. Squaring collapses pairs {x, -x} to one output,
   so |D_1| = |D_0| / 2 = 2^{n-1}.

   Inductive step:
   Assume |D_k| = |D_{k-1}| / 2. In a cyclic group of even order, squaring
   maps exactly two elements to each output (x and -x have the same square).
   Thus |D_{k+1}| = |D_k| / 2.
-/

theorem halving (k : ℕ) (hk : k < n) :
    Nat.card (D ω (k + 1)) = (Nat.card (D ω k)) / 2 := by
  -- We use the explicit cardinality formula.
  have h1 := D_card ω n hω k (by omega)
  have h2 := D_card ω n hω (k + 1) (by omega)
  rw [h1, h2]
  -- 2^{n-k} / 2 = 2^{n-(k+1)}
  have h_exp : n - k = (n - (k + 1)) + 1 := by omega
  rw [h_exp]
  rw [show 2 ^ ((n - (k + 1)) + 1) = 2 ^ (n - (k + 1)) * 2 by ring]
  simp

/- Observation: By iterating the halving, |D_k| = 2^{n-k} for all k ≤ n.
   Starting from |D_0| = 2^n, after n halvings we reach |D_n| = 1.
   In n steps, the group collapses to a single element.
-/

end Cyclic_Subgroups_and_Halving
