import Mathlib

/-
  Low Degree Proof - FRI Protocol
  
  Proof that |D_{k+1}| = |D_k| / 2 by induction,
  where D_k are cyclic subgroups of a finite field,
  and D_{k+1} = {x^2 : x ∈ D_k}.
  
  This is fundamental to the FRI (Fast Reed-Solomon IOP of Proximity)
  protocol used in zk-STARKs: each "fold" round halves the evaluation domain.
  
  The key insight is that D_k is a multiplicative cyclic subgroup, and the
  homomorphism φ(x) = x^2 halves the order because its kernel has size 2.
-/

section Direct_FRI_Proof

variable {F : Type*} [Field F] [Finite F]

-- ω is a primitive 2^n-th root of unity in F^×
variable (ω : Fˣ) (n : ℕ) (hω : orderOf ω = 2 ^ n)

include hω

/- We define D_k as the subgroup generated by ω^(2^k).
   
   In standard notation:
   - D_0 = ⟨ω⟩ (subgroup generated by ω, order 2^n)
   - D_1 = ⟨ω^2⟩ (order 2^{n-1})
   - D_2 = ⟨ω^4⟩ (order 2^{n-2})
   - ...
   - D_k = ⟨ω^(2^k)⟩ (order 2^{n-k})
   
   Note that D_{k+1} = {x^2 : x ∈ D_k} as a set.
-/

def friDomain (k : ℕ) : Subgroup Fˣ := Subgroup.zpowers (ω ^ (2 ^ k))

/- The order of ω^(2^k) is exactly 2^{n-k} (for k ≤ n).
   We use the standard formula: orderOf(g^m) = orderOf(g) / gcd(orderOf(g), m)
   
   Since orderOf(ω) = 2^n and m = 2^k, we have:
   gcd(2^n, 2^k) = 2^k (because k ≤ n)
   orderOf(ω^(2^k)) = 2^n / 2^k = 2^{n-k}
-/

theorem order_omega_pow (k : ℕ) (hk : k ≤ n) : 
    orderOf (ω ^ (2 ^ k)) = 2 ^ (n - k) := by
  rw [orderOf_pow, hω]
  -- gcd(2^n, 2^k) = 2^k when k ≤ n
  have h_gcd : Nat.gcd (2 ^ n) (2 ^ k) = 2 ^ k := by
    have h_dvd : 2 ^ k ∣ 2 ^ n := by exact Nat.pow_dvd_pow 2 (by omega)
    rw [Nat.gcd_comm]
    exact Nat.gcd_eq_left h_dvd
  rw [h_gcd]
  -- 2^n / 2^k = 2^{n-k}
  exact Nat.pow_div (by omega) (by norm_num)

/- The cardinality of D_k equals the order of its generator.
   This is a standard fact: in a finite group, |⟨a⟩| = orderOf(a).
-/

theorem friDomain_card (k : ℕ) (hk : k ≤ n) : 
    Nat.card (friDomain ω k) = 2 ^ (n - k) := by
  unfold friDomain
  rw [Nat.card_zpowers]
  exact order_omega_pow ω n hω k hk

/- 
   Main corollary: |D_k| = 2 · |D_{k+1}|.
   
   This captures the whiteboard observation: "|D_k| = 2|D_{k+1}| because it's cyclic".
   The reason is that squaring is a surjective homomorphism 
   D_k → D_{k+1} with kernel {1, -1} of size 2.
   
   Here we derive it directly from the order formula.
-/

theorem friDomain_halving (k : ℕ) (hk : k < n) :
    Nat.card (friDomain ω k) = 2 * Nat.card (friDomain ω (k + 1)) := by
  have h1 := friDomain_card ω n hω k (by omega)
  have h2 := friDomain_card ω n hω (k + 1) (by omega)
  rw [h1, h2]
  -- n - k = (n - (k+1)) + 1, hence 2^{n-k} = 2 * 2^{n-(k+1)}
  have h_exp : n - k = (n - (k + 1)) + 1 := by omega
  rw [h_exp]
  ring

/- Equivalently: |D_{k+1}| = |D_k| / 2 -/

theorem friDomain_next_card (k : ℕ) (hk : k < n) :
    Nat.card (friDomain ω (k + 1)) = Nat.card (friDomain ω k) / 2 := by
  have h := friDomain_halving ω n hω k hk
  have h_pos : Nat.card (friDomain ω (k + 1)) > 0 := by
    rw [friDomain_card ω n hω (k + 1) (by omega)]
    exact Nat.pow_pos (by norm_num)
  -- From |D_k| = 2·|D_{k+1}| we deduce |D_{k+1}| = |D_k|/2
  omega

/- 
   Full inductive proof that |D_k| = 2^{n-k}.
   
   Base case (k=0): |D_0| = |⟨ω⟩| = orderOf(ω) = 2^n. ✓
   
   Inductive step: if |D_k| = 2^{n-k}, then 
   |D_{k+1}| = |D_k|/2 = 2^{n-k}/2 = 2^{n-(k+1)}. ✓
   
   This formalizes exactly the induction argument from class.
-/

theorem friDomain_card_by_induction (k : ℕ) (hk : k ≤ n) :
    Nat.card (friDomain ω k) = 2 ^ (n - k) := by
  induction k with
  | zero =>
    -- Base case: k = 0, D_0 = ⟨ω⟩, order = 2^n
    exact friDomain_card ω n hω 0 (by omega)
  | succ k ih =>
    -- Inductive step
    have h_k_le_n : k ≤ n := by omega
    have h_k_lt_n : k < n := by omega
    
    -- Inductive hypothesis
    have h_Dk : Nat.card (friDomain ω k) = 2 ^ (n - k) := ih h_k_le_n
    
    -- Halving step
    have h_Dk1 : Nat.card (friDomain ω (k + 1)) = Nat.card (friDomain ω k) / 2 :=
      friDomain_next_card ω n hω k h_k_lt_n
    
    rw [h_Dk1, h_Dk]
    -- 2^{n-k} / 2 = 2^{n-(k+1)}
    have h_exp : n - k = (n - (k + 1)) + 1 := by omega
    rw [h_exp]
    rw [show 2 ^ ((n - (k + 1)) + 1) = 2 ^ (n - (k + 1)) * 2 by ring]
    simp

/- 
   Alternative proof of |D_{k+1}| = |D_k|/2 using the first isomorphism theorem.
   
   The homomorphism φ : D_k → D_{k+1}, φ(x) = x^2 is surjective.
   By the first isomorphism theorem: D_k / ker(φ) ≅ im(φ) = D_{k+1}.
   
   The kernel is ker(φ) = {x ∈ D_k : x^2 = 1}. 
   Since D_k is cyclic of order 2^{n-k} ≥ 2 (because k < n),
   the equation x^2 = 1 has exactly 2 solutions: x = 1 and x = -1.
   
   Therefore |D_{k+1}| = |D_k| / |ker(φ)| = |D_k| / 2.
   
   We use the standard Mathlib lemma: in a cyclic group G, the kernel of the
   homomorphism x ↦ x^d has cardinality gcd(|G|, d).
-/

theorem friDomain_kernel_size (k : ℕ) (hk : k < n) [NeZero (2 : F)] :
    let φ : (friDomain ω k) →* Fˣ := 
      MonoidHom.mk' (fun (x : (friDomain ω k)) => (x.val ^ 2)) (by intros; simp [mul_pow])
    Nat.card (MonoidHom.ker φ) = 2 := by
  intro φ
  -- In a cyclic group, the kernel of x ↦ x^d has size gcd(|G|, d)
  -- D_k is cyclic of order 2^{n-k}, and d = 2, so gcd(2^{n-k}, 2) = 2
  
  -- First, note that ker φ = ker(powMonoidHom 2) as subgroups of D_k,
  -- because both are {x ∈ D_k : x^2 = 1}
  have h_ker_eq : MonoidHom.ker φ = MonoidHom.ker (powMonoidHom 2 : (friDomain ω k) →* (friDomain ω k)) := by
    ext x
    simp only [MonoidHom.mem_ker, powMonoidHom_apply]
    -- Unfold φ manually
    change ((x : Fˣ) ^ 2 = 1) ↔ (x ^ 2 = 1)
    -- Multiplication in D_k is the restriction of that in Fˣ
    constructor
    · intro h_eq
      -- ↑x ^ 2 = 1 in Fˣ implies x^2 = 1 in D_k
      have : (x ^ 2 : (friDomain ω k)) = 1 := by
        apply Subtype.ext
        exact h_eq
      exact this
    · intro h_eq
      -- x^2 = 1 in D_k implies ↑x ^ 2 = 1 in Fˣ
      have h_eq2 : ((x ^ 2 : (friDomain ω k)) : Fˣ) = 1 := by
        rw [h_eq]
        rfl
      exact h_eq2
  
  rw [h_ker_eq]
  rw [IsCyclic.card_powMonoidHom_ker]
  -- gcd(2^{n-k}, 2) = 2 because k < n implies 2^{n-k} ≥ 2
  have h_card : Nat.card (friDomain ω k) = 2 ^ (n - k) := friDomain_card ω n hω k (by omega)
  rw [h_card]
  have h_two_dvd : 2 ∣ 2 ^ (n - k) := by
    apply dvd_pow
    · exact dvd_refl 2
    · omega
  exact Nat.gcd_eq_right h_two_dvd

end Direct_FRI_Proof

/-
  Proof summary:
  
  1. D_k = ⟨ω^(2^k)⟩ is cyclic of order 2^{n-k}.
  2. The homomorphism φ(x) = x^2 maps D_k onto D_{k+1}.
  3. Since D_k is cyclic of 2-power order, ker(φ) = {1, -1} has size 2.
  4. By the isomorphism theorem: |D_{k+1}| = |D_k| / 2.
  5. By induction: |D_k| = 2^{n-k} for all k ≤ n.
  
  This justifies the logarithmic domain reduction in the FRI protocol.
-/ 
